# Generated by Django 6.0.5 on 2026-05-24 22:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_cliente_password_alter_cliente_rfc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='concepto',
            old_name='clave',
            new_name='clave_producto',
        ),
        migrations.RemoveField(
            model_name='concepto',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='concepto',
            name='precio',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='clave',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='emisor',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='iva',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='receptor',
        ),
        migrations.AddField(
            model_name='concepto',
            name='no_cuenta_predial',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='concepto',
            name='no_identificacion',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='concepto',
            name='no_pedimento',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='concepto',
            name='unidad',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='concepto',
            name='valor_unitario',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='factura',
            name='cfdi',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='factura',
            name='codigo_postal',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='factura',
            name='csd',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='factura',
            name='efecto_comprobante',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='factura',
            name='forma_pago',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='factura',
            name='hora',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='factura',
            name='impuesto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='factura',
            name='metodo_pago',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='factura',
            name='moneda',
            field=models.CharField(default='MXN', max_length=10),
        ),
        migrations.AddField(
            model_name='factura',
            name='regimen_fiscal',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='concepto',
            name='cantidad',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='concepto',
            name='factura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conceptos', to='home.factura'),
        ),
        migrations.AlterField(
            model_name='concepto',
            name='importe',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='factura',
            name='fecha',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='factura',
            name='folio',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='factura',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='factura',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
