# Generated by Django 6.0.5 on 2026-05-25 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_clave_concepto_clave_producto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='archivo_pdf',
            field=models.FileField(blank=True, null=True, upload_to='facturas/'),
        ),
    ]
